//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace connect.Models.ibm.cm.items {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(partPropertyType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    [System.Xml.Serialization.XmlRootAttribute("properties", Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema", IsNullable=false)]
    public partial class basePropertyType {
        
        private basePropertyTypeSemanticType semanticTypeField;
        
        private basePropertyTypeACL aCLField;
        
        private basePropertyTypeCreateTime createTimeField;
        
        private basePropertyTypeCreateUserid createUseridField;
        
        private basePropertyTypeLastChangeTime lastChangeTimeField;
        
        private basePropertyTypeLastChangeUserid lastChangeUseridField;
        
        private basePropertyTypeCheckoutUserid checkoutUseridField;
        
        private basePropertyTypeCheckoutTime checkoutTimeField;
        
        private basePropertyTypeExpirationDate expirationDateField;
        
        private basePropertyTypeRetentionDate retentionDateField;
        
        private basePropertyTypeRetentionDateGMT retentionDateGMTField;
        
        private basePropertyTypeAutoDeleteDate autoDeleteDateField;
        
        private basePropertyTypeLastOperation lastOperationField;
        
        private basePropertyTypeLastRetrieveOption lastRetrieveOptionField;
        
        private basePropertyTypeParentFolder parentFolderField;
        
        private string typeField;
        
        /// <remarks/>
        public basePropertyTypeSemanticType semanticType {
            get {
                return this.semanticTypeField;
            }
            set {
                this.semanticTypeField = value;
            }
        }
        
        /// <remarks/>
        public basePropertyTypeACL ACL {
            get {
                return this.aCLField;
            }
            set {
                this.aCLField = value;
            }
        }
        
        /// <remarks/>
        public basePropertyTypeCreateTime createTime {
            get {
                return this.createTimeField;
            }
            set {
                this.createTimeField = value;
            }
        }
        
        /// <remarks/>
        public basePropertyTypeCreateUserid createUserid {
            get {
                return this.createUseridField;
            }
            set {
                this.createUseridField = value;
            }
        }
        
        /// <remarks/>
        public basePropertyTypeLastChangeTime lastChangeTime {
            get {
                return this.lastChangeTimeField;
            }
            set {
                this.lastChangeTimeField = value;
            }
        }
        
        /// <remarks/>
        public basePropertyTypeLastChangeUserid lastChangeUserid {
            get {
                return this.lastChangeUseridField;
            }
            set {
                this.lastChangeUseridField = value;
            }
        }
        
        /// <remarks/>
        public basePropertyTypeCheckoutUserid checkoutUserid {
            get {
                return this.checkoutUseridField;
            }
            set {
                this.checkoutUseridField = value;
            }
        }
        
        /// <remarks/>
        public basePropertyTypeCheckoutTime checkoutTime {
            get {
                return this.checkoutTimeField;
            }
            set {
                this.checkoutTimeField = value;
            }
        }
        
        /// <remarks/>
        public basePropertyTypeExpirationDate expirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        public basePropertyTypeRetentionDate retentionDate {
            get {
                return this.retentionDateField;
            }
            set {
                this.retentionDateField = value;
            }
        }
        
        /// <remarks/>
        public basePropertyTypeRetentionDateGMT retentionDateGMT {
            get {
                return this.retentionDateGMTField;
            }
            set {
                this.retentionDateGMTField = value;
            }
        }
        
        /// <remarks/>
        public basePropertyTypeAutoDeleteDate autoDeleteDate {
            get {
                return this.autoDeleteDateField;
            }
            set {
                this.autoDeleteDateField = value;
            }
        }
        
        /// <remarks/>
        public basePropertyTypeLastOperation lastOperation {
            get {
                return this.lastOperationField;
            }
            set {
                this.lastOperationField = value;
            }
        }
        
        /// <remarks/>
        public basePropertyTypeLastRetrieveOption lastRetrieveOption {
            get {
                return this.lastRetrieveOptionField;
            }
            set {
                this.lastRetrieveOptionField = value;
            }
        }
        
        /// <remarks/>
        public basePropertyTypeParentFolder parentFolder {
            get {
                return this.parentFolderField;
            }
            set {
                this.parentFolderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class basePropertyTypeSemanticType {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class basePropertyTypeACL {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class basePropertyTypeCreateTime {
        
        private System.DateTime valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class basePropertyTypeCreateUserid {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class basePropertyTypeLastChangeTime {
        
        private System.DateTime valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class basePropertyTypeLastChangeUserid {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class basePropertyTypeCheckoutUserid {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class basePropertyTypeCheckoutTime {
        
        private System.DateTime valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class basePropertyTypeExpirationDate {
        
        private System.DateTime valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class basePropertyTypeRetentionDate {
        
        private System.DateTime valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class basePropertyTypeRetentionDateGMT {
        
        private System.DateTime valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class basePropertyTypeAutoDeleteDate {
        
        private System.DateTime valueField;
        
        private bool valueFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool valueSpecified {
            get {
                return this.valueFieldSpecified;
            }
            set {
                this.valueFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class basePropertyTypeLastOperation {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class basePropertyTypeLastRetrieveOption {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class basePropertyTypeParentFolder {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class partPropertyType : basePropertyType {
        
        private string partIDRefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string partIDRef {
            get {
                return this.partIDRefField;
            }
            set {
                this.partIDRefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema", IsNullable=false)]
    public partial class links {
        
        private linksInbound[] inboundField;
        
        private linksOutbound[] outboundField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inbound")]
        public linksInbound[] inbound {
            get {
                return this.inboundField;
            }
            set {
                this.inboundField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("outbound")]
        public linksOutbound[] outbound {
            get {
                return this.outboundField;
            }
            set {
                this.outboundField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class linksInbound {
        
        private string fromItemField;
        
        private string linkTypeField;
        
        private string linkInfoItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string fromItem {
            get {
                return this.fromItemField;
            }
            set {
                this.fromItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string linkType {
            get {
                return this.linkTypeField;
            }
            set {
                this.linkTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string linkInfoItem {
            get {
                return this.linkInfoItemField;
            }
            set {
                this.linkInfoItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class linksOutbound {
        
        private string toItemField;
        
        private string linkTypeField;
        
        private string linkInfoItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string toItem {
            get {
                return this.toItemField;
            }
            set {
                this.toItemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string linkType {
            get {
                return this.linkTypeField;
            }
            set {
                this.linkTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string linkInfoItem {
            get {
                return this.linkInfoItemField;
            }
            set {
                this.linkInfoItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema", IsNullable=false)]
    public partial class folderSources {
        
        private folderSourcesParentItem[] parentItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parentItem")]
        public folderSourcesParentItem[] parentItem {
            get {
                return this.parentItemField;
            }
            set {
                this.parentItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class folderSourcesParentItem {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema", IsNullable=false)]
    public partial class folderContents {
        
        private folderContentsChildItem[] childItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("childItem")]
        public folderContentsChildItem[] childItem {
            get {
                return this.childItemField;
            }
            set {
                this.childItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class folderContentsChildItem {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StreamObjectType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VideoStreamObjectType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TextObjectType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    [System.Xml.Serialization.XmlRootAttribute("resourceObject", Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema", IsNullable=false)]
    public partial class LobObjectType {
        
        private LobObjectTypeLabel labelField;
        
        private LobObjectTypeURL uRLField;
        
        private string partIDRefField;
        
        private string mIMETypeField;
        
        private string sizeField;
        
        private string resourceFlagField;
        
        private string rMNameField;
        
        private string externalObjectNameField;
        
        private string resourceNameField;
        
        private string originalFileNameField;
        
        private string sMSCollNameField;
        
        /// <remarks/>
        public LobObjectTypeLabel label {
            get {
                return this.labelField;
            }
            set {
                this.labelField = value;
            }
        }
        
        /// <remarks/>
        public LobObjectTypeURL URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string partIDRef {
            get {
                return this.partIDRefField;
            }
            set {
                this.partIDRefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MIMEType {
            get {
                return this.mIMETypeField;
            }
            set {
                this.mIMETypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string resourceFlag {
            get {
                return this.resourceFlagField;
            }
            set {
                this.resourceFlagField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RMName {
            get {
                return this.rMNameField;
            }
            set {
                this.rMNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string externalObjectName {
            get {
                return this.externalObjectNameField;
            }
            set {
                this.externalObjectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string resourceName {
            get {
                return this.resourceNameField;
            }
            set {
                this.resourceNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string originalFileName {
            get {
                return this.originalFileNameField;
            }
            set {
                this.originalFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SMSCollName {
            get {
                return this.sMSCollNameField;
            }
            set {
                this.sMSCollNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class LobObjectTypeLabel {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class LobObjectTypeURL {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VideoStreamObjectType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class StreamObjectType : LobObjectType {
        
        private string playStartField;
        
        private string playStopField;
        
        private string bitRateField;
        
        private string streamDurationField;
        
        private string streamFormatField;
        
        private string accessModeField;
        
        private string streamGroupField;
        
        private string copyRateField;
        
        private string mediaStateField;
        
        private string numUsersField;
        
        private string invalidCommandsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string playStart {
            get {
                return this.playStartField;
            }
            set {
                this.playStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string playStop {
            get {
                return this.playStopField;
            }
            set {
                this.playStopField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string bitRate {
            get {
                return this.bitRateField;
            }
            set {
                this.bitRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string streamDuration {
            get {
                return this.streamDurationField;
            }
            set {
                this.streamDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string streamFormat {
            get {
                return this.streamFormatField;
            }
            set {
                this.streamFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string accessMode {
            get {
                return this.accessModeField;
            }
            set {
                this.accessModeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string streamGroup {
            get {
                return this.streamGroupField;
            }
            set {
                this.streamGroupField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string copyRate {
            get {
                return this.copyRateField;
            }
            set {
                this.copyRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string mediaState {
            get {
                return this.mediaStateField;
            }
            set {
                this.mediaStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string numUsers {
            get {
                return this.numUsersField;
            }
            set {
                this.numUsersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string invalidCommands {
            get {
                return this.invalidCommandsField;
            }
            set {
                this.invalidCommandsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class VideoStreamObjectType : StreamObjectType {
        
        private string frameRateField;
        
        private mediaStandardType mediaStandardField;
        
        private bool mediaStandardFieldSpecified;
        
        private string mediaResolutionField;
        
        private mediaEnumType mediaTypeField;
        
        private bool mediaTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string frameRate {
            get {
                return this.frameRateField;
            }
            set {
                this.frameRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public mediaStandardType mediaStandard {
            get {
                return this.mediaStandardField;
            }
            set {
                this.mediaStandardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mediaStandardSpecified {
            get {
                return this.mediaStandardFieldSpecified;
            }
            set {
                this.mediaStandardFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string mediaResolution {
            get {
                return this.mediaResolutionField;
            }
            set {
                this.mediaResolutionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public mediaEnumType mediaType {
            get {
                return this.mediaTypeField;
            }
            set {
                this.mediaTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mediaTypeSpecified {
            get {
                return this.mediaTypeFieldSpecified;
            }
            set {
                this.mediaTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public enum mediaStandardType {
        
        /// <remarks/>
        NTSC,
        
        /// <remarks/>
        PAL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public enum mediaEnumType {
        
        /// <remarks/>
        MPEG1,
        
        /// <remarks/>
        AVI,
        
        /// <remarks/>
        WAV,
        
        /// <remarks/>
        LBR,
        
        /// <remarks/>
        QT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public partial class TextObjectType : LobObjectType {
        
        private string cCSIDField;
        
        private string languageCodeField;
        
        private formatType formatField;
        
        private bool formatFieldSpecified;
        
        private string modelField;
        
        private bool textSearchableField;
        
        private bool textSearchableFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CCSID {
            get {
                return this.cCSIDField;
            }
            set {
                this.cCSIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string languageCode {
            get {
                return this.languageCodeField;
            }
            set {
                this.languageCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public formatType format {
            get {
                return this.formatField;
            }
            set {
                this.formatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool formatSpecified {
            get {
                return this.formatFieldSpecified;
            }
            set {
                this.formatFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string model {
            get {
                return this.modelField;
            }
            set {
                this.modelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool textSearchable {
            get {
                return this.textSearchableField;
            }
            set {
                this.textSearchableField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool textSearchableSpecified {
            get {
                return this.textSearchableFieldSpecified;
            }
            set {
                this.textSearchableFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    public enum formatType {
        
        /// <remarks/>
        HTML,
        
        /// <remarks/>
        XML,
        
        /// <remarks/>
        TEXT,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema", IsNullable=false)]
    public partial class itemInfo {
        
        private basePropertyType[] propertiesField;
        
        private links[] linksField;
        
        private LobObjectType[] resourceObjectField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("properties")]
        public basePropertyType[] properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("links")]
        public links[] links {
            get {
                return this.linksField;
            }
            set {
                this.linksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resourceObject")]
        public LobObjectType[] resourceObject {
            get {
                return this.resourceObjectField;
            }
            set {
                this.resourceObjectField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class HRRules {
        
        private basePropertyType propertiesField;
        
        private links linksField;
        
        private folderSourcesParentItem[] folderSourcesField;
        
        private folderContentsChildItem[] folderContentsField;
        
        private ICMBASE[] iCMBASEField;
        
        private ICMNOTELOG[] iCMNOTELOGField;
        
        private ICMANNOTATION[] iCMANNOTATIONField;
        
        private string pIDField;
        
        private string hREmployeeIDField;
        
        private string hRSSNField;
        
        private string hRFirstNameField;
        
        private string hRLastNameField;
        
        private string hRDocumentTypeField;
        
        private string hRDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
        public basePropertyType properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
        public links links {
            get {
                return this.linksField;
            }
            set {
                this.linksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
        [System.Xml.Serialization.XmlArrayItemAttribute("parentItem", IsNullable=false)]
        public folderSourcesParentItem[] folderSources {
            get {
                return this.folderSourcesField;
            }
            set {
                this.folderSourcesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
        [System.Xml.Serialization.XmlArrayItemAttribute("childItem", IsNullable=false)]
        public folderContentsChildItem[] folderContents {
            get {
                return this.folderContentsField;
            }
            set {
                this.folderContentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ICMBASE")]
        public ICMBASE[] ICMBASE {
            get {
                return this.iCMBASEField;
            }
            set {
                this.iCMBASEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ICMNOTELOG")]
        public ICMNOTELOG[] ICMNOTELOG {
            get {
                return this.iCMNOTELOGField;
            }
            set {
                this.iCMNOTELOGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ICMANNOTATION")]
        public ICMANNOTATION[] ICMANNOTATION {
            get {
                return this.iCMANNOTATIONField;
            }
            set {
                this.iCMANNOTATIONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
        public string PID {
            get {
                return this.pIDField;
            }
            set {
                this.pIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HREmployeeID {
            get {
                return this.hREmployeeIDField;
            }
            set {
                this.hREmployeeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HRSSN {
            get {
                return this.hRSSNField;
            }
            set {
                this.hRSSNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HRFirstName {
            get {
                return this.hRFirstNameField;
            }
            set {
                this.hRFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HRLastName {
            get {
                return this.hRLastNameField;
            }
            set {
                this.hRLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HRDocumentType {
            get {
                return this.hRDocumentTypeField;
            }
            set {
                this.hRDocumentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HRDate {
            get {
                return this.hRDateField;
            }
            set {
                this.hRDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ICMBASE {
        
        private basePropertyType propertiesField;
        
        private LobObjectType resourceObjectField;
        
        private string partNumberField;
        
        private string partIDField;
        
        private string pIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
        public basePropertyType properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
        public LobObjectType resourceObject {
            get {
                return this.resourceObjectField;
            }
            set {
                this.resourceObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema", DataType="integer")]
        public string partNumber {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
        public string partID {
            get {
                return this.partIDField;
            }
            set {
                this.partIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
        public string PID {
            get {
                return this.pIDField;
            }
            set {
                this.pIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ICMNOTELOG {
        
        private basePropertyType propertiesField;
        
        private LobObjectType resourceObjectField;
        
        private string partNumberField;
        
        private string partIDField;
        
        private string pIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
        public basePropertyType properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
        public LobObjectType resourceObject {
            get {
                return this.resourceObjectField;
            }
            set {
                this.resourceObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema", DataType="integer")]
        public string partNumber {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
        public string partID {
            get {
                return this.partIDField;
            }
            set {
                this.partIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
        public string PID {
            get {
                return this.pIDField;
            }
            set {
                this.pIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ICMANNOTATION {
        
        private basePropertyType propertiesField;
        
        private LobObjectType resourceObjectField;
        
        private string partNumberField;
        
        private string partIDField;
        
        private string pIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
        public basePropertyType properties {
            get {
                return this.propertiesField;
            }
            set {
                this.propertiesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
        public LobObjectType resourceObject {
            get {
                return this.resourceObjectField;
            }
            set {
                this.resourceObjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema", DataType="integer")]
        public string partNumber {
            get {
                return this.partNumberField;
            }
            set {
                this.partNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
        public string partID {
            get {
                return this.partIDField;
            }
            set {
                this.partIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.ibm.com/xmlns/db2/cm/api/1.0/schema")]
        public string PID {
            get {
                return this.pIDField;
            }
            set {
                this.pIDField = value;
            }
        }
    }
}
